version: '3.5'

services:
  products-db:
    container_name: products-db
    image: postgres
    ports:
      - 15432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=products
  products-app:
    container_name: products-app
    build:
      context: ./products
    ports:
      - 18081:8080
  cart-db:
    container_name: cart-db
    image: postgres
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cart
  cart-app:
    container_name: cart-app
    build:
      context: ./cart
    ports:
      - 18082:8080